@startuml
title Mean streets
top to bottom direction
database "Save file" {
}
package UserInterface {
    package MenuManager {}
    package SceneManager {}
}

package GameLogic {
    class Game
    package gameStorage {
        class Inventory
        class GameObject
        class HelpObject
        class Scene
    }


    package GamePlay {
        class InteractionType
        class Secretary
        class Character
        class Notification
        package GameState {
            class GameElement
            class Event
        }
    }
}

package Storage {
    class Checkpoint
}

"Save file".. Storage
UserInterface .. Game
SceneManager .. Scene

Storage .. gameStorage

InteractionType -[hidden]up- GameState
Character -[hidden]up- GameState
Secretary -[hidden]up- GameState
Notification -[hidden]up- GameState
InteractionType -[hidden]up- Character

Game - gameStorage
Game -- GamePlay

Character <|-- Secretary : is a type of
Scene <|-- Inventory : is a type of
Inventory -- "*" GameObject : contains >

Secretary -- Notification : announces >
GameObject <|-- HelpObject : is a type of

GameElement -- Event : generates >
Event -- GameElement : manipulates >

@enduml