@startuml

' Add Classes, methods, and attributes:
' --------------------
class Game {
    -Scene currentlyActive
    --
    +initiateConversation(theCharacter)
}

class Scene {
    -Character currentlyActive
    -response
    -safeQuery
    --
    +isAvailable(theCharacter)
    +getContactMethod(theCharacter)
    +getCharacter(theCharacter)
    +activate()
    +sendQuery(theQuery)
    +sanitiseInput(theQuery)
    +getPlotState()
}

class Character {
    -parsedQuery
    --
    +getInitialGreeting()
    +query(safeQuery)
    +parseQuery(theQuery)
    +formatResponse(theResponse, nextConversationOptions)

}

' Relations
' --------------------
Game --o "1" Scene

Character "*" --o Scene



@enduml