@startuml testGameDiagram
class Base{
    #x : int
    #y : int
    +Render()
    +Update()
}
class Player
class Weapon
class Armor
class GameEngine

Base <|-- Player
Player -* Weapon
Player --o Armor
Player ---* "1" GameEngine: contains

GameEngine : -Player : Player
@enduml