@startuml
title selectObject(theGameObjectName)
[-> ":Game" ++
":Game" -> ":Scene" ++ : selectObject(theGameObjectID)

":Scene" -> ":IDSanitizer" ++: validOject(gameObjectID)
note right: Early return if ID is invalid
":Scene" -> ":Scene": currentObject = getObject(gameObjectID)
":Scene" -> ":currentObject": interactionTypeOptions = formatInteractionTypes()
":Game" <- ":Scene": interactionTypeOptions
":Game" -->[: Shows list of interaction options
 

@enduml