@startuml

package testPackage {
    artifact System
    package insidePackage {
        
    }
    note bottom : "Hello"
}

package test2 {

}

testPackage .. test2
note "Link to package" as test
test .- testPackage

@enduml