@startuml

skinparam nodesep 60
skinparam ranksep 20

title Mean streets
top to bottom direction

database Database {
}
package UserInterface {
    package MenuManager {}
    package SceneManager {}
    package CharacterManager {}
}

package GameLogic {
    class Game #LightBlue {
        -Scene currentlyActive
        --
        +initiateConversation(theCharacter)
    }
    class InputSanitiser #LightBlue{
        +sanitiseInput(theQuery)
    }
    component gameStorage {
        class Inventory
        class Scene #LightBlue {
            --
            +isAvailable(theCharacter)
        }
        class PhoneBook #LightBlue{
           + getContactMethod(theCharacter)
        }
        class CharacterRepository #LightBlue{
            + getCharacter(theCharacter)
            + getInitalGreeting()
        }
    }


    package GamePlay {
        class InteractionType
        class GameElement
        class GameObject
        class HelpObject
        class Notification
        component GameObjectState {
            class Event
            class EventManager
        }
        class CharacterInterface #LightBlue{
            - -Character currentlyActive
            - response
            - safeQuery
            + create(theCharacter)
            + activate()
            + sendQuery(theQuery)
        }
        component GamePlot {
            class Secretary
            class Character #LightBlue{
                -parsedQuery
                --
                +getInitialGreeting()
                +query(safeQuery)
            }
            class PlotEngine #LightBlue{
                +getPlotState()
            }
        }
        class InteractionEngine #LightBlue{
            + create()
            +parseQuery(theQuery)
            +formatResponse(theResponse, nextConversationOptions)
        }
    }
}

package Storage {
    class Checkpoint
}

Database .. Storage
MenuManager .. Game
SceneManager .. Game
CharacterManager .. Game
Storage . gameStorage

CharacterRepository --> "*" Character


InteractionType -[hidden]up- GameObjectState
Character -[hidden]up- GameObjectState
Secretary -[hidden]up- GameObjectState
Notification -[hidden]up- GameObjectState
InteractionType -[hidden]down- Character


Game . gameStorage
Game .. GamePlay
Game -- "1" PhoneBook
Game -- "1" CharacterInterface
Character -- "1" InteractionEngine
PlotEngine - Character
CharacterInterface -- "1" Character
CharacterInterface -- "1" CharacterRepository
InputSanitiser "1" <-- CharacterInterface

Game -- "*" Scene
Checkpoint -- "*" GameElement : stores >
Checkpoint -- Inventory : stores >
Checkpoint - Game : stores >
Character <|-- Secretary : is a type of
GameElement <|-- GameObject : is a
GameElement <|-- Character : is a
Scene - "*" GameElement : contains >
Scene <|-- Inventory : is a type of
Inventory -- "*" GameObject : contains >
EventManager "1" - Scene : Has >
EventManager - Event : generates >
Event -- Notification : generates >
Event -- GameElement : manipulates >
Secretary -- Notification : announces >
GameObject <|-- HelpObject : is a type of
GameObject <|-- Notification : is a
GameObject -- "*" InteractionType : has >
@enduml
