@startuml

title selectInteraction(theInteractionType)
[-> ":Game" ++: selectInteraction(theInteractionType)
":Game" -> "currentScene:Scene" ++ : getOptionList(theInteractionType)
"currentScene:Scene" -> "current:gameObject" ++ : getFormattedList(theInteractionType)
note right: Game object is already selected from past diagram
"current:gameObject" -> "current:gameObject": interactionType current = getInteraction(theInteractionType)
"current:gameObject" -> "current:InteractionType": optionList = listOptions()
return optionList
return optionList
":Game" -->[: optionList
 
@enduml