@startuml

title selectInteraction(theInteractionType)
[-> ":Game" ++: newInteraction(theInteractionType)
":Game" -> "currentScene:Scene" ++ : getInteractionList(theInteractionType)
"currentScene:Scene" -> "current:gameObject" ++ : selectInteraction(theInteractionType)
note right: Game object is already selected from past diagram
"current:gameObject" -> "current:gameObject": interactionType current = getInteraction(theInteractionType)
"current:gameObject" -> "current:InteractionType": optionList = listOptions()
return optionList
return optionList
":Game" -->[: Shows options for interaction, requests input
 
@enduml