@startuml

title startInteraction()
[-> ":Scene" ++ : startInteraction()
":Scene" -> ":eventManager" ++ : startEvent(selectedGameObject)
":eventManager" --> ":Event" ** : create()
":eventManager" -> ":Event" ++: doEvent(selectedGameObject)
":Event" -> "selected:gameObject" ++: startInteraction()
"selected:gameObject" -> "selected:gameObject": executeInteraction()
"selected:gameObject" -> "selected:gameObject": string eventResponse = createEventResponse()
return response 
return response 
return response
return response

@enduml