[-> "GameObjectInterface:" ++: startinteraction()
"GameObjectInterface:" -> "CurrentObject:GameObject" ++: startCurrentInteraction()
"CurrentObject:GameObject" -> "CurrentType:InteractionType": interactionresponse = executeInteraction()
"CurrentObject:GameObject" -> "CurrentObject:GameObject": CurrentState = changeState(interactionresponse)
return interactionresponse
return interactionresponse







