@startuml selectInteraction

[-> "GameObjectInterface:" ++: selectInteraction(theInteractionType)
"GameObjectInterface:" -> "CurrentObject:GameObject" ++: startInteraction(String theInteractionType)
"CurrentObject:GameObject" -> "CurrentObject:GameObject": CurrentType = selectStrategy(theInteractionType)
return
"GameObjectInterface:" -> "CurrentObject:GameObject" ++:returnList = listCurrentInteractionOptions()
"CurrentObject:GameObject" -> "CurrentType:InteractionType" ++: returnList = listOptions()
return returnList
return returnList
return returnList

@enduml